INSERT INTO users (name, email, password, profile_picture, banner_picture, description, location, created_at) 
VALUES 
('Aldwin Bautista', 'Aldiwn@email.com', '$2b$10$B0Yjjbke2i0cRJ.31OtBYOxuYVB9BcEGwopaVlOU9svnVVd2tXrXG','https://i.imgur.com/QMntCB7.png','https://i.imgur.com/qdVnqRJ.jpg','I love being in deep thoughts and providing for the ones I care', 'Vancouver, BC, Canada', '2022-11-25'),
('Jakob Bollman', 'Jakob@email.com', '$2b$10$B0Yjjbke2i0cRJ.31OtBYOxuYVB9BcEGwopaVlOU9svnVVd2tXrXG','https://i.imgur.com/g7PB1Nk.jpg','https://i.imgur.com/UigZzwS.jpg','I love skiing and people with amazing smile like me. Hit me up if you like to smile', 'Vancouver, BC, Canada', '2022-11-25'),
('Jaxson Berg', 'Jaxson@email.com', '$2b$10$B0Yjjbke2i0cRJ.31OtBYOxuYVB9BcEGwopaVlOU9svnVVd2tXrXG','https://i.imgur.com/lgDJDBu.png','https://i.imgur.com/LVQui1O.png','I love coding and playing story driven games. I also have majestic hair', 'Calgary, AB, Canada', '2022-11-25'),
('Kasey Valdez', 'Kasey@email.com', '$2b$10$B0Yjjbke2i0cRJ.31OtBYOxuYVB9BcEGwopaVlOU9svnVVd2tXrXG','https://i.imgur.com/QaxJGky.jpg','https://i.imgur.com/CIIjCnO.jpg','I love using profile pic not of myself and big chungus', 'Vancouver, BC, Canada', '2022-11-25'),
('Emily Vilett', 'Emily@email.com', '$2b$10$B0Yjjbke2i0cRJ.31OtBYOxuYVB9BcEGwopaVlOU9svnVVd2tXrXG','https://i.imgur.com/fxBIvnA.jpg','https://i.imgur.com/f1WF67l.jpg','I am in dire need of friends for my only friends are a plushy parrot and a turnip', 'Vancouver, BC, Canada', '2022-11-25'),
('Taylor Smith', 'Taylor@email.com', '$2b$10$B0Yjjbke2i0cRJ.31OtBYOxuYVB9BcEGwopaVlOU9svnVVd2tXrXG','https://i.imgur.com/NVyfREI.jpg','https://i.imgur.com/zXvRlG7.png','I love over-dressing for casual situations Please do not talk to me if you dont own a $1000+ suit.', 'Vancouver, BC, Canada', '2022-11-25'),
('Ray Yu', 'Ray@email.com', '$2b$10$B0Yjjbke2i0cRJ.31OtBYOxuYVB9BcEGwopaVlOU9svnVVd2tXrXG','https://i.imgur.com/JNxypzl.png','https://i.imgur.com/RWoCBv3.png','I run a discord server w/over 5000+ members Please dm me if you want to be part of the best cohort.', 'Vancouver, BC, Canada', '2022-11-25'),
('Minha Kim', 'Minha@email.com', '$2b$10$B0Yjjbke2i0cRJ.31OtBYOxuYVB9BcEGwopaVlOU9svnVVd2tXrXG','https://i.imgur.com/laelNmQ.jpeg','https://i.imgur.com/gc7foG7.jpg','Shawl enthusiast and a strawberry farmer. Love meeting with people named Anouk and kasey ', 'Vancouver, BC, Canada', '2022-11-25')
;